[build]
  # Build configuration
  publish = "."
  
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Form settings
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Force form detection
[context.production.environment]
  NODE_VERSION = "18"

# Enable form processing
[build.environment]
  NETLIFY_USE_YARN = "true"